# SPDX-License-Identifier: MIT
"""Public PaloNexus Python SDK API."""

from .context import atask, task
from .credentials import (
    AsyncCredentialProvider,
    Credential,
    CredentialAcquisitionCancelled,
    CredentialUnavailable,
    InvalidCredentialDeadline,
    SyncCredentialProvider,
)
from .errors import (
    ApprovalExpired,
    ApprovalRequired,
    ApprovalScopeMismatch,
    AuthenticationFailed,
    AuthorizationUnavailable,
    CredentialRevoked,
    IdempotencyConflict,
    InvalidDecision,
    InvalidRequest,
    MissingIdentity,
    ModelValidationError,
    PaloNexusError,
    PolicyDenied,
    UnsupportedProtocol,
)
from .keystore import (
    EphemeralKeyStore,
    InvalidKeyIdentifier,
    InvalidKeyMaterial,
    KeyNotFound,
    KeyStore,
    KeyStoreClosed,
    KeyStoreCorrupt,
    KeyStoreError,
    KeyStoreUnavailable,
)
from .models import ActionRequest, ActionTarget, DecisionOutcome, TaskContext
from .protocol import ActionRequestBuilder
from .redaction import Redactor
from .retry import (
    CompletionState,
    RetryDecision,
    RetryFailure,
    RetryPolicy,
    RetryPolicyError,
    RetryReason,
)

__all__ = [
    "ActionRequest",
    "ActionRequestBuilder",
    "ActionTarget",
    "ApprovalExpired",
    "ApprovalRequired",
    "ApprovalScopeMismatch",
    "AsyncCredentialProvider",
    "AuthenticationFailed",
    "AuthorizationUnavailable",
    "CompletionState",
    "Credential",
    "CredentialAcquisitionCancelled",
    "CredentialUnavailable",
    "CredentialRevoked",
    "DecisionOutcome",
    "EphemeralKeyStore",
    "IdempotencyConflict",
    "InvalidDecision",
    "InvalidCredentialDeadline",
    "InvalidKeyIdentifier",
    "InvalidKeyMaterial",
    "InvalidRequest",
    "KeyNotFound",
    "KeyStore",
    "KeyStoreClosed",
    "KeyStoreCorrupt",
    "KeyStoreError",
    "KeyStoreUnavailable",
    "MissingIdentity",
    "ModelValidationError",
    "PaloNexusError",
    "PolicyDenied",
    "Redactor",
    "RetryDecision",
    "RetryFailure",
    "RetryPolicy",
    "RetryPolicyError",
    "RetryReason",
    "SyncCredentialProvider",
    "TaskContext",
    "UnsupportedProtocol",
    "atask",
    "task",
]
