# SPDX-License-Identifier: MIT
from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class SourceRevisionBuildHook(BuildHookInterface[Any]):
    PLUGIN_NAME = "source-revision"
    _BUILD_PATTERN = re.compile(
        r"# generated by the PaloNexus build hook\n"
        r'SOURCE_REVISION = "([0-9a-f]{40})"\n'
    )
    _SDIST_PATTERN = re.compile(
        r"# generated by the PaloNexus build hook\n"
        r'SDIST_MARKER = "palonexus-sdk-sdist-v1"\n'
        r'SOURCE_REVISION = "([0-9a-f]{40})"\n'
    )

    def _source_revision(self) -> str:
        package = Path(self.root) / "src" / "palonexus"
        marker = package / "_sdist_provenance.py"
        evidence = package / "_build.py"
        if marker.exists():
            try:
                marker_content = marker.read_text(encoding="utf-8")
                evidence_content = evidence.read_text(encoding="utf-8")
            except OSError as error:
                raise RuntimeError(
                    "packaged SDK source revision evidence is unavailable"
                ) from error
            marker_match = self._SDIST_PATTERN.fullmatch(marker_content)
            evidence_match = self._BUILD_PATTERN.fullmatch(evidence_content)
            if (
                marker_match is None
                or evidence_match is None
                or marker_match.group(1) != evidence_match.group(1)
            ):
                raise RuntimeError("packaged SDK source revision evidence is invalid")
            revision = marker_match.group(1)
        else:
            try:
                revision = subprocess.run(
                    ["git", "rev-parse", "--verify", "HEAD"],
                    cwd=self.root,
                    check=True,
                    capture_output=True,
                    text=True,
                ).stdout.strip()
            except (OSError, subprocess.CalledProcessError) as error:
                raise RuntimeError(
                    "exact SDK source revision is unavailable"
                ) from error
        if re.fullmatch(r"[0-9a-f]{40}", revision) is None:
            raise RuntimeError("exact SDK source revision is invalid")
        return revision

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        del version
        revision = self._source_revision()
        generated = Path(self.directory) / "palonexus-build" / "_build.py"
        generated.parent.mkdir(parents=True, exist_ok=True)
        generated.write_text(
            "# generated by the PaloNexus build hook\n"
            f'SOURCE_REVISION = "{revision}"\n',
            encoding="utf-8",
        )
        destination = (
            "src/palonexus/_build.py"
            if self.target_name == "sdist"
            else "palonexus/_build.py"
        )
        build_data.setdefault("force_include", {})[str(generated)] = destination
        if self.target_name == "sdist":
            marker = Path(self.directory) / "palonexus-build" / "_sdist_provenance.py"
            marker.write_text(
                "# generated by the PaloNexus build hook\n"
                'SDIST_MARKER = "palonexus-sdk-sdist-v1"\n'
                f'SOURCE_REVISION = "{revision}"\n',
                encoding="utf-8",
            )
            build_data.setdefault("force_include", {})[str(marker)] = (
                "src/palonexus/_sdist_provenance.py"
            )


def get_build_hook() -> type[SourceRevisionBuildHook]:
    return SourceRevisionBuildHook
